### ISSUE TITLE
关于normalize

### ISSUE THREAD

**Issue by ChrisKong93** [yeyupiaoling/Tensorflow-FaceRecognition#2]
你好，我有个问题，在用netron查看pb模型的时候我发现，pb模型最后已经做了一次normalize
那么代码推理的时候
```python
emb_arrays = face_sess.run(embeddings, feed_dict=feed_dict)
emb_arrays = sklearn.preprocessing.normalize(emb_arrays)
```
这里是不是就重复了

**Comment by yeyupiaoling** [comment]
@ChrisKong93 这个是为了在这里计算两张人脸的相似度的
https://github.com/yeyupiaoling/Tensorflow-FaceRecognition/blob/bc567fb53dc11554bfaf612f3a21045f7ab24876/utils/utils.py#L15

**Comment by ChrisKong93** [comment]
@yeyupiaoling 我看一下，明白了，这里应该是算余弦距离吧，余弦距离需要做一次normalize。
我之前facenet是用欧氏距离去做的，就不用再做一次normalize
