### ISSUE TITLE
新手请教一下模型问题

### ISSUE THREAD

**Issue by x-lambda** [yeyupiaoling/Tensorflow-FaceRecognition#3]
在`models/mobilefacenet_model`目录下有个pb文件，请问这个是训练好的模型文件吗？

`https://github.com/yeyupiaoling/Tensorflow-FaceRecognition/blob/master/models/mobilefacenet_model/MobileFaceNet_9925_9680.pb`

**Comment by yeyupiaoling** [comment]
是的是的
